notifications:
  email:
    recipients:
      - pengzhengfa@aliyun.com
  on_success: change
  on_failure: always

language: java

matrix:
  include:
    # On OSX, run with default JDK only.
    # - os: osx
    # On Linux, run with specific JDKs only.
    - os: linux
      env: CUSTOM_JDK="oraclejdk8"

jdk:
  - openjdk11
  - openjdk8

before_install:
  - echo 'MAVEN_OPTS="$MAVEN_OPTS -Xmx1024m -XX:MaxPermSize=512m -XX:+BytecodeVerificationLocal"' >> ~/.mavenrc
  - cat ~/.mavenrc
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then jdk_switcher use "$CUSTOM_JDK"; fi

script:
  - mvn clean install -DskipITs -Dmaven.test.skip=true
  - mvn -Dmaven.test.skip=true clean install -U
  - mvn -Dmaven.test.skip=true clean

after_success:
  - mvn clean package -Pit-test